module.exports = {
    AUTH_START : "AUTH_START",
    AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
    AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
    AUTH_SIGNUP_SUCCESS: "AUTH_SIGNUP_SUCCESS",
    AUTH_SIGNUP_FAILED: "AUTH_SIGNUP_FAILED",
    RESET: "RESET"
}